// HeroIcon's names can be found here: https://ng-icons.github.io/ng-icons/#/browse-icons
import {
  heroUser,
  heroUsers,
  heroHome,
  heroCog6Tooth,
  heroBell,
  heroAcademicCap,
  heroArchiveBoxArrowDown,
  heroInformationCircle,
  heroFaceSmile,
  heroPhoto,
  heroLink,
  heroLockClosed,         // Used by IconPicker, ForumStructureTree, and Login
  heroMapPin,
  heroStar,
  heroSun,
  heroMoon,
  heroChevronDown,        // Used by IconPicker internally
  heroArrowRightEndOnRectangle, // Used by Login
  // Add any other globally used HeroIcons here
  heroGift,
  heroGlobeAlt,
  heroHomeModern,
  heroFilm,
  heroCake,
  heroMusicalNote,
  heroShoppingCart,
  heroScissors,
  heroWifi,
  heroTag,
  heroRocketLaunch,
  heroWrenchScrewdriver,
  heroClock,
  heroChatBubbleBottomCenterText,
  heroChatBubbleLeft,
  heroChatBubbleLeftRight,
  heroEye,
  heroCog,
  heroQuestionMarkCircle,
  heroCheckBadge,
  heroMegaphone,
  heroUserCircle,
  heroQueueList,
  heroChartBar,
  heroHandThumbUp,
  heroHandThumbDown,
  heroMagnifyingGlass,
  heroPaperClip,
  heroChartPie,
  heroChartBarSquare,
  heroSparkles,
  heroPencilSquare,
} from '@ng-icons/heroicons/outline';

import {
  heroUserSolid,
  heroUsersSolid,
  heroHomeSolid,
  heroCog6ToothSolid,
  heroBellSolid,
  heroAcademicCapSolid,
  heroArchiveBoxArrowDownSolid,
  heroInformationCircleSolid,
  heroFaceSmileSolid,
  heroPhotoSolid,
  heroLinkSolid,
  heroLockClosedSolid,         // Used by IconPicker, ForumStructureTree, and Login
  heroMapPinSolid,
  heroStarSolid,
  heroSunSolid,
  heroMoonSolid,
  heroChevronDownSolid,        // Used by IconPicker internally
  heroArrowRightEndOnRectangleSolid, // Used by Login
  // Add any other globally used HeroIcons here
  heroGiftSolid,
  heroGlobeAltSolid,
  heroHomeModernSolid,
  heroFilmSolid,
  heroCakeSolid,
  heroMusicalNoteSolid,
  heroShoppingCartSolid,
  heroScissorsSolid,
  heroWifiSolid,
  heroTagSolid,
  heroRocketLaunchSolid,
  heroWrenchScrewdriverSolid,
  heroClockSolid,
  heroChatBubbleBottomCenterTextSolid,
  heroChatBubbleLeftSolid,
  heroChatBubbleLeftRightSolid,
  heroEyeSolid,
  heroCogSolid,
  heroQuestionMarkCircleSolid,
  heroCheckBadgeSolid,
  heroMegaphoneSolid,
  heroUserCircleSolid,
  heroQueueListSolid,
  heroChartBarSolid,
  heroHandThumbUpSolid,
  heroHandThumbDownSolid,
  heroMagnifyingGlassSolid,
  heroPaperClipSolid,
  heroChartPieSolid,
  heroChartBarSquareSolid,
  heroSparklesSolid,
  heroPencilSquareSolid,
} from '@ng-icons/heroicons/solid';

/**
 * Defines the structure for an icon that can be picked.
 */
export interface AppIconDefinition {
  displayName: string; // User-friendly name for display in the picker
  name: string;        // The string key used by ng-icon (e.g., "heroUser")
}

/**
 * List of icons available for selection in the IconPickerComponent.
 * The 'name' property MUST match a key in APP_ICON_OBJECT_MAP.
 */
export const APP_PICKER_AVAILABLE_ICONS: AppIconDefinition[] = [
  { displayName: 'User', name: 'heroUserSolid' },
  { displayName: 'Users', name: 'heroUsersSolid' },
  { displayName: 'Home', name: 'heroHomeSolid' },
  { displayName: 'Settings', name: 'heroCog6ToothSolid' },
  { displayName: 'Bell', name: 'heroBellSolid' },
  { displayName: 'Education', name: 'heroAcademicCapSolid' },
  { displayName: 'Archive', name: 'heroArchiveBoxArrowDownSolid' },
  { displayName: 'Smile', name: 'heroFaceSmileSolid' },
  { displayName: 'Photo', name: 'heroPhotoSolid' },
  { displayName: 'Link', name: 'heroLinkSolid' },
  { displayName: 'Lock', name: 'heroLockClosedSolid' },
  { displayName: 'Map Pin', name: 'heroMapPinSolid' },
  { displayName: 'Star', name: 'heroStarSolid' },
  { displayName: 'Gift', name: 'heroGiftSolid' },
  { displayName: 'Globe Alternative', name: 'heroGlobeAltSolid' },
  { displayName: 'Home Modern', name: 'heroHomeModernSolid' },
  { displayName: 'Film', name: 'heroFilmSolid' },
  { displayName: 'Cake', name: 'heroCakeSolid' },
  { displayName: 'Musical Note', name: 'heroMusicalNoteSolid' },
  { displayName: 'Shopping Cart', name: 'heroShoppingCartSolid' },
  { displayName: 'Scissors', name: 'heroScissorsSolid' },
  { displayName: 'Wifi', name: 'heroWifiSolid' },
  { displayName: 'Tag', name: 'heroTagSolid' },
  { displayName: 'Rocket Launch', name: 'heroRocketLaunchSolid' },
  { displayName: 'Wrench Screwdriver', name: 'heroWrenchScrewdriverSolid' },
  { displayName: 'Clock', name: 'heroClockSolid' },
  { displayName: 'Chat Bubble Left Right', name: 'heroChatBubbleLeftRightSolid' },
  { displayName: 'Eye', name: 'heroEyeSolid' },
  { displayName: 'Cog', name: 'heroCogSolid' },
  { displayName: 'Question Mark Circle', name: 'heroQuestionMarkCircleSolid' },
  { displayName: 'Check Badge', name: 'heroCheckBadgeSolid' },
  { displayName: 'Megaphone', name: 'heroMegaphoneSolid' },
  { displayName: 'Chart Pie', name: 'heroChartPieSolid' },
  { displayName: 'Chart Bar Square', name: 'heroChartBarSquareSolid' },
];

/**
 * A comprehensive map of all HeroIcon string names to their actual icon objects.
 * This is used by `provideIcons` in any component that needs to render these icons.
 * It should include all icons from APP_PICKER_AVAILABLE_ICONS plus any
 * icons used internally by components or by other components in the app.
 */
export const APP_ICONS = {
  heroUser,
  heroUsers,
  heroHome,
  heroCog6Tooth,
  heroBell,
  heroAcademicCap,
  heroArchiveBoxArrowDown,
  heroInformationCircle,
  heroFaceSmile,
  heroPhoto,
  heroLink,
  heroLockClosed,
  heroMapPin,
  heroStar,
  heroSun,
  heroMoon,
  heroChevronDown, // For IconPicker's internal chevron
  heroArrowRightEndOnRectangle, // For Login component
  heroGift,
  heroGlobeAlt,
  heroHomeModern,
  heroFilm,
  heroCake,
  heroMusicalNote,
  heroShoppingCart,
  heroScissors,
  heroWifi,
  heroTag,
  heroRocketLaunch,
  heroWrenchScrewdriver,
  heroClock,
  heroChatBubbleBottomCenterText,
  heroChatBubbleLeft,
  heroChatBubbleLeftRight,
  heroEye,
  heroCog,
  heroQuestionMarkCircle,
  heroCheckBadge,
  heroMegaphone,
  heroUserCircle,
  heroQueueList,
  heroChartBar,
  heroHandThumbUp,
  heroHandThumbDown,
  heroMagnifyingGlass,
  heroPaperClip,
  heroChartPie,
  heroChartBarSquare,
  heroSparkles,
  heroPencilSquare,
  // Solid icons
  heroUserSolid,
  heroUsersSolid,
  heroHomeSolid,
  heroCog6ToothSolid,
  heroBellSolid,
  heroAcademicCapSolid,
  heroArchiveBoxArrowDownSolid,
  heroInformationCircleSolid,
  heroFaceSmileSolid,
  heroPhotoSolid,
  heroLinkSolid,
  heroLockClosedSolid,         // Used by IconPicker, ForumStructureTree, and Login
  heroMapPinSolid,
  heroStarSolid,
  heroSunSolid,
  heroMoonSolid,
  heroChevronDownSolid,        // Used by IconPicker internally
  heroArrowRightEndOnRectangleSolid, // Used by Login
  heroGiftSolid,
  heroGlobeAltSolid,
  heroHomeModernSolid,
  heroFilmSolid,
  heroCakeSolid,
  heroMusicalNoteSolid,
  heroShoppingCartSolid,
  heroScissorsSolid,
  heroWifiSolid,
  heroTagSolid,
  heroRocketLaunchSolid,
  heroWrenchScrewdriverSolid,
  heroClockSolid,
  heroChatBubbleBottomCenterTextSolid,
  heroChatBubbleLeftSolid,
  heroChatBubbleLeftRightSolid,
  heroEyeSolid,
  heroCogSolid,
  heroQuestionMarkCircleSolid,
  heroCheckBadgeSolid,
  heroMegaphoneSolid,
  heroUserCircleSolid,
  heroQueueListSolid,
  heroChartBarSolid,
  heroHandThumbUpSolid,
  heroHandThumbDownSolid,
  heroMagnifyingGlassSolid,
  heroPaperClipSolid,
  heroChartPieSolid,
  heroChartBarSquareSolid,
  heroSparklesSolid,
  heroPencilSquareSolid,
  // Add any other globally used HeroIcons here
};
